name: om
channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - joblib
  - ipython
  - tqdm
  - matplotlib
  - statsmodels
  - tensorboard
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - scikit-learn
  - scikit-image
  - imageio
  - biopython
  - astropy
  - openpyxl
  - jax
  - tabulate
  - faiss-gpu
  - napari
  - networkx
  - gitpython
  - nd2reader
  - sqlalchemy
  - more-itertools
  - magicgui
  - seaborn
  - numba
  - pyyaml
  - pytest
  - pyqt5-sip
  - itables
  - pivottablejs